//
//  IDPAWStyleKit.h
//  IDPAuthoringWorkspace
//
//  Created by 能登 要 on 2015/06/23.
//  Copyright (c) 2015 Irimasu Densan Planning. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface IDPAWStyleKit : NSObject

// Drawing Methods
+ (void)drawTrackerWithFrame: (CGRect)frame;

@end
